language: python

php:
  - 2.7

before_script:
  - pip install -r src/api/requirements.txt

script:
  - python tests/api/run.py

notifications:
  email:
    recipients: tetsuwo.oishi+travis-ci@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
