language: python

php:
  - 2.7

before_script:
  - pip install -r src/api/requirements.txt
  - cp src/api/config/databases.py.sample src/api/config/databases.py
  - mysql -u root < src/api/data/sql/mysql_createdb.sql
  - mysql -u root vimmanbot < src/api/data/sql/mysql_schema.sql

script:
  - python -m unittest discover -s tests/api/ -p '*_test.py'

notifications:
  email:
    recipients: project.omosan+vimmanbot@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
